include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    always_declare_return_types: true
    avoid_dynamic_calls: true
    avoid_print: true
    directives_ordering: true
    prefer_final_locals: true
    unnecessary_lambdas: true
